version: "3.7"

services:
  nginx:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - 9506:80

  php-fpm:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php_fpm
    build:
      context: ./.docker/php
    env_file:
      - .env
    user: 1000:1000
    ports:
      - "9005:9003"
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
    working_dir: /app
